Tests
gmzych/learn-appium-android-tests pull request #4
Opened 2021-10-29 14:35 UTC by gmzych

First few tests which I've made recently

2021-11-02 22:05 UTC, DawidBastek requested changes
Good job! 👍  Few small fixes and we are ready to go to the next level 😎

2021-11-04 22:18 UTC, gmzych commented on tests/base_tests.py
> +        mapelement = self.driver.find_element_by_xpath('/hierarchy/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayou
sure :), I will be using snake_case for variables, methods, functions and CamelCase for classes

2021-11-04 22:18 UTC, gmzych commented on tests/base_tests.py
> +        self.driver.find_element_by_xpath('/hierarchy/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.LinearLayout/android
Ok, it's corrected in another PR

2021-11-18 17:22 UTC, DawidBastek submitted a review, later dismissed

2021-12-01 14:53 UTC, DawidBastek approved these changes
Looks good for this stage!
One thing, you could install `pylint` for your project. If you're using PyCharm here is the link:
https://plugins.jetbrains.com/plugin/11084-pylint

2021-12-01 16:33 UTC, merged